language: node_js
node_js:
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13

os:
  - windows
  - linux
  - osx

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

before-script:
  - npm install
script:
  - npm run build
